# Generated by Django 5.2.17 on 2026-09-06 15:58

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
        ("content_planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("s3_key", models.TextField()),
                ("duration_ms", models.IntegerField()),
                ("mood", models.CharField(blank=True, default="", max_length=64)),
                ("bpm", models.IntegerField(blank=True, null=True)),
                ("license_type", models.CharField(max_length=64)),
                ("license_document_url", models.TextField(blank=True, default="")),
                ("attribution_required", models.BooleanField(default=False)),
                ("attribution_text", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "music_tracks",
            },
        ),
        migrations.CreateModel(
            name="VideoJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                            ("regeneration", "Regeneration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("queued", "Queued"),
                            ("generating_script", "Generating script"),
                            ("script_ready", "Script ready"),
                            ("moderating_script", "Moderating script"),
                            ("generating_voice", "Generating voice"),
                            ("voice_ready", "Voice ready"),
                            ("generating_visuals", "Generating visuals"),
                            ("visuals_ready", "Visuals ready"),
                            ("assembling", "Assembling"),
                            ("assembled", "Assembled"),
                            ("moderating_final", "Moderating final"),
                            ("moderation_review", "Moderation review"),
                            ("moderation_rejected", "Moderation rejected"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("changes_requested", "Changes requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("upload_queued", "Upload queued"),
                            ("uploading", "Uploading"),
                            ("uploaded", "Uploaded"),
                            ("published", "Published"),
                            ("youtube_rejected", "YouTube rejected"),
                            ("retrying", "Retrying"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("deleted_on_youtube", "Deleted on YouTube"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("script", "Script"),
                            ("voice", "Voice"),
                            ("visuals", "Visuals"),
                            ("assembly", "Assembly"),
                            ("moderation", "Moderation"),
                            ("upload", "Upload"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("script_text", models.TextField(blank=True, default="")),
                ("script_meta", models.JSONField(blank=True, default=dict)),
                ("language", models.CharField(blank=True, default="", max_length=10)),
                ("duration_sec", models.IntegerField(blank=True, null=True)),
                ("final_video_s3_key", models.TextField(blank=True, default="")),
                ("thumbnail_s3_key", models.TextField(blank=True, default="")),
                (
                    "preview_token",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("preview_expires_at", models.DateTimeField(blank=True, null=True)),
                ("approval_requested_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("regeneration_count", models.SmallIntegerField(default=0)),
                (
                    "youtube_video_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("youtube_url", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "youtube_upload_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "youtube_rejection_reason",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("is_platform_generated", models.BooleanField(default=True)),
                ("deleted_on_youtube", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("retry_count", models.SmallIntegerField(default=0)),
                (
                    "total_cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approval_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_jobs",
                        to="channels.youtubechannel",
                    ),
                ),
                (
                    "parent_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regenerations",
                        to="video_pipeline.videojob",
                    ),
                ),
                (
                    "preference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_jobs",
                        to="content_planning.contentpreference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "video_jobs",
            },
        ),
        migrations.CreateModel(
            name="VideoAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("script", "Script"),
                            ("audio_voice", "Audio (voice)"),
                            ("audio_music", "Audio (music)"),
                            ("visual_clip", "Visual clip"),
                            ("subtitle", "Subtitle"),
                            ("thumbnail", "Thumbnail"),
                            ("final_video", "Final video"),
                        ],
                        max_length=20,
                    ),
                ),
                ("s3_key", models.TextField()),
                ("mime_type", models.CharField(blank=True, default="", max_length=64)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                (
                    "license_ref",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("sequence_index", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="video_pipeline.videojob",
                    ),
                ),
            ],
            options={
                "db_table": "video_assets",
            },
        ),
        migrations.CreateModel(
            name="VideoJobStep",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("script", "Script"),
                            ("voice", "Voice"),
                            ("visuals", "Visuals"),
                            ("assembly", "Assembly"),
                            ("moderation", "Moderation"),
                            ("upload", "Upload"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attempt", models.SmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                (
                    "provider_request_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("output_ref", models.TextField(blank=True, default="")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="video_pipeline.videojob",
                    ),
                ),
            ],
            options={
                "db_table": "video_job_steps",
            },
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(
                fields=["user", "status"], name="ix_video_jobs_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(
                fields=["channel", "published_at"], name="ix_video_jobs_channel_pub"
            ),
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(fields=["status"], name="ix_video_jobs_status"),
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(
                fields=["scheduled_for"], name="ix_video_jobs_scheduled_for"
            ),
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(fields=["youtube_video_id"], name="ix_video_jobs_yt_id"),
        ),
        migrations.AddIndex(
            model_name="videoasset",
            index=models.Index(fields=["job", "kind"], name="ix_video_assets_job_kind"),
        ),
        migrations.AddIndex(
            model_name="videojobstep",
            index=models.Index(
                fields=["job", "stage", "attempt"], name="ix_video_job_steps_lookup"
            ),
        ),
    ]
