# Generated by Django 5.2.17 on 2026-09-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_pipeline", "0002_beat_schedule_expire_approvals"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="generation_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
