# Generated by Django 5.2.17 on 2026-09-17 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_pipeline", "0003_videojob_generation_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="moderation_approved_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="VideoRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("reason", models.TextField()),
                ("findings", models.JSONField(default=dict)),
                (
                    "previous_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_revision",
                        to="video_pipeline.videojob",
                    ),
                ),
                (
                    "replacement_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_origin",
                        to="video_pipeline.videojob",
                    ),
                ),
                (
                    "root_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_history",
                        to="video_pipeline.videojob",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("root_job", "number"),
                        name="unique_video_revision_number",
                    )
                ],
            },
        ),
    ]
