# Generated by Django 5.2.17 on 2026-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_pipeline", "0004_videojob_moderation_approved_sha256_videorevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="moderation_metadata_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
