# Generated by Django 5.2.17 on 2026-09-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_datarequest_sessionmeta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="locale",
            field=models.CharField(
                choices=[
                    ("ru", "Russian"),
                    ("en", "English"),
                    ("fr", "French"),
                    ("zh", "Mandarin Chinese"),
                    ("ko", "Korean"),
                    ("de", "German"),
                    ("ar", "Modern Standard Arabic"),
                    ("tr", "Turkish"),
                    ("uz", "Uzbek"),
                    ("fa", "Persian"),
                    ("hi", "Hindi"),
                    ("ur", "Urdu"),
                    ("ky", "Kyrgyz"),
                    ("kk", "Kazakh"),
                    ("tg", "Tajik"),
                    ("tk", "Turkmen"),
                    ("az", "Azerbaijani"),
                    ("ka", "Georgian"),
                    ("es", "Spanish"),
                    ("ar-EG", "Egyptian Arabic"),
                    ("ha", "Hausa"),
                    ("pt", "Portuguese"),
                    ("it", "Italian"),
                    ("ja", "Japanese"),
                    ("id", "Indonesian"),
                    ("bn", "Bengali"),
                    ("vi", "Vietnamese"),
                    ("th", "Thai"),
                    ("pl", "Polish"),
                    ("uk", "Ukrainian"),
                ],
                default="ru",
                max_length=10,
            ),
        ),
    ]
