# Generated by Django 5.2.17 on 2026-09-17 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0003_plan_ai_budget_enabled_plan_discount_ends_at_and_more"),
        ("video_pipeline", "0005_videojob_moderation_metadata_sha256"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramConfig",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("channel_id", models.CharField(blank=True, max_length=64)),
                ("bot_username", models.CharField(blank=True, max_length=64)),
                (
                    "token_secret_ref",
                    models.CharField(default="TELEGRAM_BOT_TOKEN", max_length=100),
                ),
                (
                    "webhook_secret_ref",
                    models.CharField(default="TELEGRAM_WEBHOOK_SECRET", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelegramUpdate",
            fields=[
                (
                    "update_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StarsOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("telegram_id", models.BigIntegerField()),
                ("stars", models.PositiveIntegerField()),
                ("net_usd", models.DecimalField(decimal_places=2, max_digits=14)),
                ("tax_usd", models.DecimalField(decimal_places=2, max_digits=14)),
                ("charge_id", models.CharField(max_length=255, null=True, unique=True)),
                ("paid_at", models.DateTimeField(null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="billing.plan"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelegramArchive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("channel_id", models.CharField(max_length=64)),
                ("checksum", models.CharField(max_length=64)),
                ("parts", models.JSONField(default=list)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("error", models.CharField(blank=True, max_length=200)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_pipeline.videojob",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelegramIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
