# Generated by Django 5.2.17 on 2026-09-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramconfig",
            name="stars_net_usd",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
