# Generated by Django 5.2.17 on 2026-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_integration", "0002_telegramconfig_stars_net_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="starsorder",
            name="precheckout_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
