# Generated by Django 5.2.17 on 2026-09-06 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("video_pipeline", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("script", "Script"),
                            ("audio", "Audio"),
                            ("visual", "Visual"),
                            ("final", "Final"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("flag", "Flag"),
                            ("block", "Block"),
                        ],
                        max_length=10,
                    ),
                ),
                ("categories", models.JSONField(blank=True, default=dict)),
                ("threshold_config", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "review_decision",
                    models.CharField(
                        blank=True,
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("review_reason", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="video_pipeline.videojob",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "moderation_logs",
                "indexes": [
                    models.Index(fields=["job"], name="ix_moderation_logs_job"),
                    models.Index(
                        fields=["verdict", "reviewed_at"],
                        name="ix_moderation_logs_verdict",
                    ),
                ],
            },
        ),
    ]
