# Generated by Django 5.2.17 on 2026-09-07 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("videos_quota", models.IntegerField(default=0)),
                ("videos_generated", models.IntegerField(default=0)),
                ("videos_published", models.IntegerField(default=0)),
                ("regenerations_used", models.IntegerField(default=0)),
                (
                    "total_cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("reserved_job_ids", models.JSONField(blank=True, default=list)),
                ("exhausted_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_counters",
                        to="billing.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_counters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "usage_counters",
                "indexes": [
                    models.Index(
                        fields=["user", "period_end"], name="ix_usage_counters_user_end"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "period_start"),
                        name="uq_usage_counter_user_period",
                    )
                ],
            },
        ),
    ]
