# Generated by Django 5.2.17 on 2026-09-17 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_commercial_plans"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIWalletHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=200, unique=True)),
                ("amount_usd", models.DecimalField(decimal_places=6, max_digits=16)),
                ("released", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.aiwallet",
                    ),
                ),
            ],
        ),
    ]
