# Generated by Django 5.2.17 on 2026-09-06 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("channels", "0001_initial"),
        ("contracts", "0001_initial"),
        ("video_pipeline", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueShareStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("gross_revenue", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "platform_share_pct",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                (
                    "platform_share_amount",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "creator_share_amount",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("video_count", models.IntegerField(default=0)),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("finalized", "Finalized"),
                            ("invoiced", "Invoiced"),
                            ("paid", "Paid"),
                            ("disputed", "Disputed"),
                            ("written_off", "Written off"),
                            ("carried_forward", "Carried forward"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("disputed_at", models.DateTimeField(blank=True, null=True)),
                ("dispute_reason", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("carried_forward_from", models.UUIDField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_share_statements",
                        to="contracts.contract",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_share_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "revenue_share_statements",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("revenue_share", "Revenue share"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("void", "Void"),
                            ("uncollectible", "Uncollectible"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.SmallIntegerField(default=0)),
                ("pdf_url", models.TextField(blank=True, default="")),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="revenue.revenuesharestatement",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "entry_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "ref_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("statement", "Statement"),
                            ("payout", "Payout"),
                            ("subscription", "Subscription"),
                            ("adjustment", "Adjustment"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ref_id", models.UUIDField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("description", models.TextField(blank=True, default="")),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("reversal_of", models.BigIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ledger_entries",
                "indexes": [
                    models.Index(
                        fields=["ref_type", "ref_id"], name="ix_ledger_entries_ref"
                    ),
                    models.Index(
                        fields=["user", "occurred_at"],
                        name="ix_ledger_entries_user_time",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RevenueRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "youtube_video_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("youtube_analytics", "YouTube Analytics"),
                            ("adsense", "AdSense"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.BigIntegerField(default=0)),
                ("estimated_minutes_watched", models.BigIntegerField(default=0)),
                (
                    "estimated_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "estimated_ad_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "cpm",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "rpm",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_final", models.BooleanField(default=False)),
                ("synced_at", models.DateTimeField()),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_records",
                        to="channels.youtubechannel",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_records",
                        to="video_pipeline.videojob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "revenue_records",
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="ix_revenue_records_user_date"
                    ),
                    models.Index(
                        fields=["is_final", "date"],
                        name="ix_revenue_records_final_date",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "channel", "youtube_video_id", "date"),
                        name="uq_revenue_record_upsert_key",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="revenuesharestatement",
            constraint=models.UniqueConstraint(
                fields=("user", "period_start", "period_end"),
                name="uq_statement_period",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "status"], name="ix_invoices_user_status"
            ),
        ),
    ]
