# Generated by Django 5.2.17 on 2026-09-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("revenue", "0003_beat_schedule_period_close"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenuesharestatement",
            name="platform_share_pct",
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
    ]
