# Generated by Django 5.2.17 on 2026-09-06 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("body_markdown", models.TextField()),
                ("body_sha256", models.CharField(editable=False, max_length=64)),
                ("locale", models.CharField(default="en", max_length=5)),
                (
                    "revenue_share_platform_pct",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                (
                    "revenue_share_creator_pct",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                ("effective_from", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contract_versions",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True, default="")),
                ("body_sha256", models.CharField(max_length=64)),
                ("pdf_s3_key", models.TextField(blank=True, default="")),
                ("consent_revenue_share", models.BooleanField(default=False)),
                ("consent_publish_to_channel", models.BooleanField(default=False)),
                ("consent_data_processing", models.BooleanField(default=False)),
                ("consent_marketing", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="contracts.contractversion",
                    ),
                ),
            ],
            options={
                "db_table": "contracts",
                "indexes": [
                    models.Index(fields=["user"], name="ix_contracts_user"),
                    models.Index(fields=["status"], name="ix_contracts_status"),
                ],
            },
        ),
    ]
