# Generated by Django 5.2.17 on 2026-09-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_seed_contract_v1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractversion",
            name="revenue_share_creator_pct",
            field=models.DecimalField(decimal_places=2, default=70, max_digits=5),
        ),
        migrations.AlterField(
            model_name="contractversion",
            name="revenue_share_platform_pct",
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
    ]
