# Generated by Django 5.2.17 on 2026-09-26 16:30

import core.fields
import django.core.validators
import django.db.models.deletion
import payoneer.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoneerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(max_length=120)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('checkout_enabled', models.BooleanField(default=False)),
                ('is_default_checkout', models.BooleanField(default=False)),
                ('merchant_code', models.CharField(blank=True, max_length=120)),
                ('payment_token_enc', core.fields.EncryptedTextField(blank=True, editable=True, null=True)),
                ('division', models.CharField(blank=True, max_length=120)),
                ('notification_token_enc', core.fields.EncryptedTextField(default=payoneer.models.new_notification_token, editable=True)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('is_default_payouts', models.BooleanField(default=False)),
                ('program_id', models.CharField(blank=True, max_length=64)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret_enc', core.fields.EncryptedTextField(blank=True, editable=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_check_ok', models.BooleanField(blank=True, null=True)),
                ('last_check_detail', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-is_active', 'label'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_checkout', True)), fields=('is_default_checkout',), name='one_default_payoneer_checkout'), models.UniqueConstraint(condition=models.Q(('is_default_payouts', True)), fields=('is_default_payouts',), name='one_default_payoneer_payouts')],
            },
        ),
        migrations.CreateModel(
            name='PayoneerPayee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('payee_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('inactive', 'Inactive')], default='invited', max_length=12)),
                ('provider_status', models.CharField(blank=True, max_length=60)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payees', to='payoneer.payoneeraccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payoneer_payees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PayoneerPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.CharField(max_length=200)),
                ('client_reference_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('submitting', 'Submitting'), ('pending', 'Pending'), ('transferred', 'Transferred'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='submitting', max_length=12)),
                ('provider_status', models.CharField(blank=True, max_length=60)),
                ('payout_id', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='payoneer.payoneeraccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='payoneer.payoneerpayee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payoneerpayee',
            constraint=models.UniqueConstraint(fields=('account', 'payee_id'), name='unique_payoneer_payee'),
        ),
    ]
