# Generated by Django 5.2.17 on 2026-09-06 15:58

import core.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdSenseAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("adsense_account_id", models.CharField(max_length=64, unique=True)),
                (
                    "access_token_enc",
                    core.fields.EncryptedTextField(
                        blank=True, editable=True, null=True
                    ),
                ),
                (
                    "refresh_token_enc",
                    core.fields.EncryptedTextField(
                        blank=True, editable=True, null=True
                    ),
                ),
                ("token_key_version", models.SmallIntegerField(default=1)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "granted_scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="disconnected",
                        max_length=20,
                    ),
                ),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adsense_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "adsense_accounts",
                "indexes": [
                    models.Index(fields=["user"], name="ix_adsense_accounts_user")
                ],
            },
        ),
        migrations.CreateModel(
            name="YouTubeChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("youtube_channel_id", models.CharField(max_length=64, unique=True)),
                (
                    "channel_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "channel_handle",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("thumbnail_url", models.TextField(blank=True, default="")),
                ("subscriber_count", models.BigIntegerField(blank=True, null=True)),
                ("video_count", models.BigIntegerField(blank=True, null=True)),
                ("is_monetized", models.BooleanField(blank=True, null=True)),
                (
                    "monetization_source",
                    models.CharField(
                        choices=[
                            ("api", "Detected via API"),
                            ("self_declared", "Self-declared"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "access_token_enc",
                    core.fields.EncryptedTextField(
                        blank=True, editable=True, null=True
                    ),
                ),
                (
                    "refresh_token_enc",
                    core.fields.EncryptedTextField(
                        blank=True, editable=True, null=True
                    ),
                ),
                ("token_key_version", models.SmallIntegerField(default=1)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "granted_scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="disconnected",
                        max_length=20,
                    ),
                ),
                (
                    "last_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "youtube_channels",
                "indexes": [
                    models.Index(fields=["user"], name="ix_yt_channels_user"),
                    models.Index(fields=["status"], name="ix_yt_channels_status"),
                ],
            },
        ),
    ]
