# Generated by Django 5.2.17 on 2026-09-06 15:58

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("niche", models.CharField(max_length=64)),
                ("custom_brief", models.TextField(blank=True, default="")),
                ("brand_voice", models.TextField(blank=True, default="")),
                (
                    "banned_topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("video_duration_sec", models.IntegerField()),
                (
                    "aspect_ratio",
                    models.CharField(
                        choices=[("16:9", "16:9"), ("9:16", "9:16")],
                        default="16:9",
                        max_length=8,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("publish_time_local", models.TimeField()),
                ("publish_timezone", models.CharField(max_length=64)),
                (
                    "publish_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "youtube_privacy_status",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("youtube_category_id", models.CharField(default="22", max_length=8)),
                ("made_for_kids", models.BooleanField(default=False)),
                (
                    "approval_mode",
                    models.CharField(
                        choices=[
                            ("review_required", "Review required"),
                            ("auto", "Auto-publish"),
                        ],
                        default="review_required",
                        max_length=20,
                    ),
                ),
                ("auto_publish_on_timeout", models.BooleanField(default=False)),
                ("voice_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "music_style",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("is_paused", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_preferences",
                        to="channels.youtubechannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_preferences",
                "indexes": [
                    models.Index(fields=["channel"], name="ix_content_prefs_channel")
                ],
            },
        ),
    ]
