# Generated by Django 5.2.17 on 2026-09-17 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0003_beat_schedules"),
        ("content_planning", "0002_seed_beat_schedule"),
        ("video_pipeline", "0003_videojob_generation_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpreference",
            name="automatic_schedule_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ContentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("request_key", models.UUIDField()),
                (
                    "horizon",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("item_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("generating", "generating"),
                            ("ready", "ready"),
                            ("approved", "approved"),
                            ("failed", "failed"),
                            ("canceled", "canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("preference_snapshot", models.JSONField(default=dict)),
                ("analysis", models.JSONField(default=dict)),
                ("summary", models.TextField(blank=True, default="")),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_plans",
                        to="channels.youtubechannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentPlanItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=100)),
                ("brief", models.TextField()),
                ("rationale", models.TextField(blank=True, default="")),
                ("scheduled_for", models.DateTimeField()),
                ("selected", models.BooleanField(default=True)),
                (
                    "job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_item",
                        to="video_pipeline.videojob",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content_planning.contentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddConstraint(
            model_name="contentplan",
            constraint=models.UniqueConstraint(
                fields=("user", "request_key"), name="unique_plan_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentplanitem",
            constraint=models.UniqueConstraint(
                fields=("plan", "position"), name="unique_plan_position"
            ),
        ),
    ]
