# Generated by Django 5.2.17 on 2026-09-22 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_planning', '0003_contentpreference_automatic_schedule_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('daily_message_limit', models.PositiveSmallIntegerField(default=20)),
                ('guidance', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, max_length=1000)),
                ('audience_region', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='uz', max_length=20)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=64)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistantTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_key', models.UUIDField()),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'request_key'), name='assistant_user_request')],
            },
        ),
    ]
