# Generated by Django 5.2.17 on 2026-09-06 18:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("video_pipeline", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiCredentialConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("llm", "LLM (script generation)"),
                            ("tts", "Text-to-speech"),
                            ("video_gen", "Video generation"),
                            ("music", "Music generation"),
                            ("moderation", "Content moderation"),
                            ("translation", "Translation"),
                            ("stt", "Speech-to-text"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="openrouter | elevenlabs | azure_tts | runway | veo | svd | suno | openai_moderation | aws_rekognition | deepl | whisper",
                        max_length=64,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider-side model id, e.g. 'anthropic/claude-sonnet-4.5'. Never hardcoded in application code (SPEC section 9).",
                        max_length=128,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=100,
                        help_text="Lower value = tried first when failing over (F2 routing).",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-secret provider parameters: base_url, temperature, thresholds, timeouts, per-token prices. NEVER put API keys here.",
                    ),
                ),
                (
                    "unit_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=14, null=True
                    ),
                ),
                (
                    "cost_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("per_1k_tokens", "Per 1k tokens"),
                            ("per_char", "Per character"),
                            ("per_second", "Per second"),
                            ("per_clip", "Per clip"),
                            ("per_request", "Per request"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "secret_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the env var / Django setting holding the API key (e.g. OPENROUTER_API_KEY) — NOT the key itself (C-5, FR-84).",
                        max_length=128,
                    ),
                ),
                ("rate_limit_per_min", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "api_credentials_config",
                "indexes": [
                    models.Index(
                        fields=["service", "is_active"],
                        name="ix_api_creds_service_active",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True), ("is_primary", True)
                        ),
                        fields=("service",),
                        name="uq_api_credentials_one_primary_per_service",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ApiUsageLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("llm", "LLM (script generation)"),
                            ("tts", "Text-to-speech"),
                            ("video_gen", "Video generation"),
                            ("music", "Music generation"),
                            ("moderation", "Content moderation"),
                            ("translation", "Translation"),
                            ("stt", "Speech-to-text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                (
                    "operation",
                    models.CharField(
                        help_text="e.g. script_generation, script_moderation",
                        max_length=64,
                    ),
                ),
                (
                    "units",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("unit_type", models.CharField(blank=True, default="", max_length=32)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=14),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("http_status", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "request_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_usage_logs",
                        to="video_pipeline.videojob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_usage_logs",
                "indexes": [
                    models.Index(fields=["job"], name="ix_api_usage_job"),
                    models.Index(
                        fields=["provider", "created_at"],
                        name="ix_api_usage_provider_time",
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="ix_api_usage_user_time"
                    ),
                ],
            },
        ),
    ]
