# Generated by Django 5.2.17 on 2026-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0002_seed_default_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiusagelog",
            name="completion_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apiusagelog",
            name="pricing_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="apiusagelog",
            name="prompt_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
