# Generated by Django 5.2.17 on 2026-09-22 22:00

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_apiusagelog_completion_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_enc', core.fields.EncryptedTextField(editable=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('tested_config_version', models.DateTimeField(blank=True, null=True)),
                ('provider_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='providers.apicredentialconfig')),
            ],
        ),
    ]
