# Generated by Django 5.2.17 on 2026-09-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=2000)),
                ('link_url', models.URLField(max_length=2000)),
                ('caption', models.CharField(blank=True, default='', max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_affiliate', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBanner',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(default='Hamkorlarimiz', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='Biz bilan hamkorlik qilayotgan tashkilotlar va xizmatlar', max_length=240)),
                ('animation_enabled', models.BooleanField(default=True)),
                ('animation_seconds', models.PositiveSmallIntegerField(default=35)),
            ],
        ),
    ]
