# Generated by Django 5.2.17 on 2026-09-22 16:58

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "event_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NumberOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "country_code",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z]{2}$")
                        ],
                    ),
                ),
                ("country_name", models.CharField(max_length=80)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("youtube", "youtube"),
                            ("telegram", "telegram"),
                            ("whatsapp", "whatsapp"),
                            ("other", "other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "number_type",
                    models.CharField(
                        choices=[("mobile", "Mobile"), ("voip", "VoIP")], max_length=10
                    ),
                ),
                ("provider", models.CharField(max_length=80)),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "rental_days",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("is_visible", models.BooleanField(default=True)),
                ("sales_enabled", models.BooleanField(default=False)),
                ("contract_confirmed", models.BooleanField(default=False)),
                ("compatibility_confirmed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["country_name", "service", "name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("price_usd__gte", 1), ("rental_days__gte", 1)
                        ),
                        name="number_offer_positive_price_duration",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NumberOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("request_key", models.UUIDField()),
                ("offer_name", models.CharField(max_length=120)),
                ("service", models.CharField(max_length=20)),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rental_days", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("active", "active"),
                            ("expired", "expired"),
                            ("canceled", "canceled"),
                            ("refund_requested", "refund_requested"),
                            ("refunded", "refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("checkout_id", models.CharField(blank=True, max_length=255)),
                ("checkout_url", models.URLField(blank=True, max_length=2048)),
                ("payment_intent", models.CharField(blank=True, max_length=255)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "terms_version",
                    models.CharField(default="2026-09-22", max_length=30),
                ),
                ("refund_reason", models.CharField(blank=True, max_length=500)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="virtual_numbers.numberoffer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncomingSMS",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("event_id", models.CharField(max_length=160, unique=True)),
                ("sender_enc", core.fields.EncryptedTextField(editable=True)),
                ("body_enc", core.fields.EncryptedTextField(editable=True)),
                ("received_at", models.DateTimeField()),
                ("delete_after", models.DateTimeField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="virtual_numbers.numberorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "number",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+[1-9][0-9]{6,14}$"
                            )
                        ],
                    ),
                ),
                ("provider_reference", models.CharField(max_length=160, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("available", "available"),
                            ("reserved", "reserved"),
                            ("assigned", "assigned"),
                            ("retired", "retired"),
                        ],
                        default="available",
                        max_length=12,
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="numbers",
                        to="virtual_numbers.numberoffer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="numberorder",
            name="phone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="virtual_numbers.phonenumber",
            ),
        ),
        migrations.AddConstraint(
            model_name="numberorder",
            constraint=models.UniqueConstraint(
                fields=("user", "request_key"), name="unique_number_order_request"
            ),
        ),
    ]
