# Generated by Django 5.2.17 on 2026-09-22 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_numbers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="numberoffer",
            name="base_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="numberoffer",
            name="tax_basis",
            field=models.CharField(
                choices=[
                    ("base", "Provider cost"),
                    ("subtotal", "Cost plus platform fee"),
                ],
                default="base",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="numberorder",
            name="payment_provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe / Visa"),
                    ("paypal", "PayPal"),
                    ("allpay", "allpay.net"),
                ],
                default="stripe",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="numberorder",
            name="price_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
