# Generated by Django 5.2.17 on 2026-09-26 16:30

import core.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payoneer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('director_name', models.CharField(blank=True, max_length=160)),
                ('acting_basis', models.CharField(default='Ustav', max_length=120)),
                ('acting_basis_en', models.CharField(default='the Charter', max_length=120)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(default='Toshkent shahri', max_length=80)),
                ('city_en', models.CharField(default='Tashkent, Republic of Uzbekistan', max_length=80)),
                ('tin', models.CharField(blank=True, max_length=20, verbose_name='STIR / TIN')),
                ('bank_name', models.CharField(blank=True, max_length=160)),
                ('bank_account', models.CharField(blank=True, max_length=40)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('swift', models.CharField(blank=True, max_length=11)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vat_note', models.CharField(blank=True, help_text='Printed after the price in resident contracts, e.g. «QQS hisobga olinmagan».', max_length=200)),
                ('sales_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('revision_rounds', models.PositiveSmallIntegerField(default=2)),
                ('support_months', models.PositiveSmallIntegerField(default=1)),
                ('page_limit', models.PositiveSmallIntegerField(default=1)),
                ('languages', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'price_usd'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('request_key', models.UUIDField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('contract_type', models.CharField(choices=[('resident', 'Resident of Uzbekistan (individual)'), ('non_resident', 'Foreign citizen (individual)')], max_length=12)),
                ('project_name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending_payment', 'Awaiting payment'), ('paid', 'Paid'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded')], default='pending_payment', max_length=16)),
                ('contract_enc', core.fields.EncryptedTextField(editable=True)),
                ('contract_version', models.CharField(max_length=20)),
                ('contract_sha256', models.CharField(max_length=64)),
                ('accepted_at', models.DateTimeField()),
                ('accepted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_user_agent', models.CharField(blank=True, max_length=300)),
                ('checkout_id', models.CharField(blank=True, max_length=120)),
                ('checkout_url', models.URLField(blank=True, max_length=2048)),
                ('charge_id', models.CharField(blank=True, max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.CharField(blank=True, max_length=1000)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='web_service_orders', to='payoneer.payoneeraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_service_orders', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_services.servicepackage')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'request_key'), name='unique_web_service_request')],
            },
        ),
    ]
