# Generated by Django 5.2.17 on 2026-09-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("staff", "Staff"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("action", models.CharField(max_length=128)),
                ("resource_type", models.CharField(max_length=64)),
                ("resource_id", models.CharField(max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_logs",
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="ix_audit_logs_resource",
                    ),
                    models.Index(
                        fields=["actor_id", "created_at"], name="ix_audit_logs_actor"
                    ),
                    models.Index(
                        fields=["action", "created_at"], name="ix_audit_logs_action"
                    ),
                ],
            },
        ),
    ]
